### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by ghost** [arnavb/SnakeGame#4]
`}

void debugKeyboard() {
    while (!antKeyboard.checkKeyState(KEY_PRESS_ESC)) {
        cout << "Key Code : " << (int) inportb(0x60) << endl;
    }
}

void main() {
    clrscr();
    
    //debugKeyboard();
    runGame();
}
'

**Comment by arnavb** [comment]
Sorry, could you clarify what this issue is about? As of now, this seems like a bunch of random code.
